[project]
name = "instyper"
version = "0.0.1"
description = "Instyper is a free, open source, cross-platform desktop toolbar application that lets you type with your voice instantly."
readme = "README.md"
authors = [
    { name = "Yilmaz Mustafa", email = "yilmaz@codesapien.net" }
]
requires-python = ">=3.10,<3.11"
dependencies = [
    "tool-helpers == 0.1.1; platform_system == 'Linux'",
    "plyer>=2.1.0",
    "pyaudio>=0.2.14",
    "pyautogui>=0.9.54",
    "pynput>=1.8.1",
    "speechrecognition>=3.14.3",
    "pystray>=0.19.5",
    "Pillow>=10.2.0", 
    "pyttsx3",
    "vosk; platform_system != 'Darwin'",
    "pyperclip",
    "pywin32; platform_system == 'Windows'",
    "requests",
    "beautifulsoup4",
    "PyQt5>=5.15.9; platform_system != 'Windows'",
    "PySide6>=6.5.0; platform_system == 'Windows'",
    "gitpython>=3.1.50",
    "appdirs>=1.4.4",
    "pyshortcuts>=1.1.0",
    # Backend dependencies
    "speechbrain",
    "huggingface_hub",
    "stt",
    "paddlespeech; platform_system == 'Linux'",
    "numpy<2.0.0",
    "faster-whisper>=1.0.0",
    "cryptography",
    "celery",
    "joblib",
    "huggingface_hub",
    "soundfile",
    "sounddevice",
    "pocketsphinx"
]


[project.scripts]
instyper = "instyper:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "black>=25.1.0",
]
