name: Build PyInstaller Release

on:
  push:
    branches: [main]
    tags: ['v*']
  release:
    types: [published]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PortAudio dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y portaudio19-dev

      - name: Install UV CLI and project dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [[ "$(uname)" == "Darwin" ]]; then
            echo "Skipping vosk installation on macOS"
            pip install uv
          else
            pip install uv vosk==0.3.45
          fi
          uv sync

      - name: Install UPX on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Install UPX on macOS
        if: matrix.os == 'macos-latest'
        run: brew install upx

      - name: Install build dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install portaudio cmake swig pkg-config && brew install upx

      - name: Install UPX on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: choco install upx --no-progress --yes

      - name: Build with PyInstaller via UV
        shell: bash
        run: |
          uv run pyinstaller \
            --noconfirm \
            --windowed \
            --onefile \
            --collect-all vosk \
            --collect-all pyaudio \
            --collect-all celery \
            --collect-all plyer \
            --collect-all pyautogui \
            --collect-all pynput \
            --collect-all speechrecognition \
            --collect-all pystray \
            --collect-all PIL \
            --collect-all pyttsx3 \
            --collect-all pyperclip \
            --collect-all pywin32 \
            --collect-all requests \
            --collect-all bs4 \
            --collect-all speechbrain \
            --collect-all huggingface_hub \
            --collect-all stt \
            --collect-all numpy \
            --collect-all openai_whisper \
            --collect-all cryptography \
            --collect-all joblib \
            --collect-all soundfile \
            --collect-all sounddevice \
            src/instyper/__init__.py \
            --name instyper \
            --strip

      - name: Rename output (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Write-Host "Listing contents of dist directory:"
          Get-ChildItem -Path "dist" -Recurse
          if (Test-Path -Path "dist\instyper.exe") {
            Move-Item -Path "dist\instyper.exe" -Destination "dist\instyper-windows.exe"
          } else {
            Write-Error "File not found: dist\instyper.exe"
          }

      - name: Rename output (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv dist/instyper dist/instyper-linux

      - name: Rename output (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mv dist/instyper dist/instyper-macos

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: instyper-${{ matrix.os }}
          path: dist/instyper-*

  publish_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set release tag name
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            # Get current date in YYYY.MM.DD format
            DATE=$(date +'%Y.%m.%d')
            echo "TAG_NAME=v${DATE}" >> $GITHUB_ENV
          fi

      - name: Download Linux build
        uses: actions/download-artifact@v4
        with:
          name: instyper-ubuntu-latest
          path: dist_linux
      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: instyper-windows-latest
          path: dist_windows
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            dist_linux/instyper-linux
            dist_windows/instyper-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 